# Generated by Django 4.2.6 on 2024-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.CharField(max_length=150),
        ),
    ]
