# Generated by Django 4.2.6 on 2024-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Resource'), ('career', 'Career Resource'), ('general', 'General Resource')], default='unknown', max_length=20),
        ),
    ]
