# Generated by Django 5.0.4 on 2024-04-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
