# Generated by Django 5.0.4 on 2024-04-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_email_user_username_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileCreated',
            field=models.BooleanField(default=False),
        ),
    ]
