# Generated by Django 5.0.4 on 2024-04-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_branch_user_company_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='mobileNumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='passout_year',
            new_name='passoutYear',
        ),
    ]
