# Generated by Django 5.0.4 on 2024-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_date_of_birth_user_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areaOfInterest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profileType',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('student', 'Student'), ('alumni', 'Alumni')], max_length=10, null=True),
        ),
    ]
