# Generated by Django 5.0.4 on 2024-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_areaofinterest_user_profiletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
