# Generated by Django 4.2.6 on 2024-05-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
