# Generated by Django 4.2.6 on 2024-05-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_savedjob_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
