# Generated by Django 4.2.6 on 2024-05-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
